name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
    # Only build if these specific files change:
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'steps/**'  # Your python scripts
  workflow_dispatch: # Keep this so you can still force a build manually
